name: rrw_mvc_refac
description: Railroad Wars game.

publish_to: 'Google Play'

version: 0.0.1+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  mvc_pattern: ^7.0.0

  adaptive_theme: ^2.2.0
  flutter_native_splash: ^1.2.1
  flutter_launcher_icons: ^0.9.1
  cupertino_icons: ^1.0.2
  flutter_staggered_grid_view: ^0.4.0
  flutter_svg: ^0.22.0

  #the following two packages are associated with
  # 'generated' and 'l10n' folders in the project
  intl: ^0.17.0
  flutter_localizations:
    sdk: flutter
  #you can manipulating only with 'l10n'
  #e.g. adding or removing supported languages you need
  # FLutter intl plugin for your IDE
  #
  #to add new line translations to .arb files, 
  #remember the following:
  #
  #the keys should be identical in all .arb files,
  #change the values according to the translation
  #
  #for more see:
  #
  #https://pub.dev/packages/intl
  #
  #https://localizely.com/flutter-localization-workflow/
  #
  #https://redirect.is/sqnj7ri - we used this
  

  http: ^0.13.3

  shared_preferences: ^2.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/png/
    - assets/svg/

  fonts:
    - family: CustomIcons
      fonts:
        - asset: assets/fonts/CustomIcons.ttf

flutter_intl:
  enabled: true
  main_locale: ru_RU
